name: InvSeePlugin
version: 1.0
main: com.yourplugin.invsee.InvSeePlugin
api-version: 1.20
commands:
  invsee:
    description: Melihat inventory dan ender chest pemain.
    usage: /invsee <nama_player>
permissions:
  invsee.use:
    description: Mengizinkan akses perintah /invsee
    default: op
